/**
 * ينزّل الخطوط من Google Fonts مرة وحدة ويحطها داخل المشروع.
 *
 * Downloads the web fonts once and rewrites the CSS to point at local copies.
 * Self-hosting buys three things:
 *   1. the Content-Security-Policy can stay at `default-src 'none'` with no
 *      third-party origins punched through it,
 *   2. no request to a third party on every page load (no IP/UA leak),
 *   3. the app still renders correctly with no network.
 *
 * Run with:  npm run fonts
 */

import fs from 'node:fs/promises';
import path from 'node:path';

const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Cairo:wght@600;900&family=IBM+Plex+Sans+Arabic:wght@400;500;600&family=Archivo:wght@600;800;900&display=swap';

// Only the subsets this app actually renders. Dropping the rest cuts ~80% of bytes.
const KEEP_SUBSETS = new Set(['arabic', 'latin', 'latin-ext']);

const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36';

const root = path.resolve(import.meta.dirname, '..');
const fontsDir = path.join(root, 'public', 'fonts');
const cssOut = path.join(root, 'public', 'css', 'fonts.css');

async function main() {
  const res = await fetch(CSS_URL, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`Google Fonts CSS request failed: ${res.status}`);
  const css = await res.text();

  await fs.mkdir(fontsDir, { recursive: true });
  await fs.mkdir(path.dirname(cssOut), { recursive: true });

  // The CSS is a flat list of "/* subset */ @font-face { ... }" blocks.
  const blocks = css.split('/*').slice(1);
  const out = [
    '/* خطوط محلية — مولّدة بأمر: npm run fonts. لا تعدّلها يدوياً. */',
    '/* Generated by scripts/fetch-fonts.mjs — do not edit by hand. */',
    '',
  ];
  const downloaded = new Map();

  for (const raw of blocks) {
    const subset = raw.slice(0, raw.indexOf('*/')).trim();
    if (!KEEP_SUBSETS.has(subset)) continue;

    const block = raw.slice(raw.indexOf('*/') + 2);
    const family = /font-family:\s*'([^']+)'/.exec(block)?.[1];
    // Variable fonts declare a range ("font-weight: 600 900") in a single file.
    // Capturing only the first number would silently drop the bold weights.
    const weight = /font-weight:\s*([\d\s]+?);/.exec(block)?.[1]?.trim();
    const stretch = /font-stretch:\s*([^;]+);/.exec(block)?.[1]?.trim();
    const url = /url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/.exec(block)?.[1];
    if (!family || !weight || !url) continue;

    const file = `${family.replace(/\s+/g, '')}-${weight.replace(/\s+/g, '_')}-${subset}.woff2`;
    if (!downloaded.has(url)) {
      const fontRes = await fetch(url, { headers: { 'User-Agent': UA } });
      if (!fontRes.ok) throw new Error(`font download failed: ${url} → ${fontRes.status}`);
      await fs.writeFile(path.join(fontsDir, file), Buffer.from(await fontRes.arrayBuffer()));
      downloaded.set(url, file);
      console.log('↓', file);
    }

    const unicodeRange = /unicode-range:\s*([^;]+);/.exec(block)?.[1]?.trim();
    out.push(
      '@font-face {',
      `  font-family: '${family}';`,
      '  font-style: normal;',
      `  font-weight: ${weight};`,
      ...(stretch ? [`  font-stretch: ${stretch};`] : []),
      '  font-display: swap;',
      `  src: url('../fonts/${downloaded.get(url)}') format('woff2');`,
      ...(unicodeRange ? [`  unicode-range: ${unicodeRange};`] : []),
      '}',
      ''
    );
  }

  if (downloaded.size === 0) throw new Error('no font files were downloaded');
  await fs.writeFile(cssOut, out.join('\n'), 'utf8');
  console.log(`\n✓ ${downloaded.size} ملف خط → public/fonts/`);
  console.log('✓ public/css/fonts.css');
}

main().catch((err) => {
  console.error('\n✗ فشل تنزيل الخطوط:', err.message);
  console.error('  التطبيق بيشتغل عادي بخطوط النظام، بس الشكل بيختلف شوي.');
  process.exit(1);
});
